version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./backend:/app/backend

  frontend:
    build: ./frontend/backTest
    ports:
      - "5173:5173"
    depends_on:
      - backend

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery_worker:
    build: ./backend
    command: celery -A app.celery_app.celery worker --loglevel=info -P gevent
    depends_on:
      - backend
      - redis
    volumes:
      - ./backend:/app/backend

  celery_beat:
    build: ./backend
    command: celery -A app.celery_app.celery beat --loglevel=info
    depends_on:
      - redis

volumes:
  pgdata: 