"""add fields to fetched_data

Revision ID: ec079dada6f6
Revises: 
Create Date: 2025-06-12 00:17:17.841856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec079dada6f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fetched_data', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('fetched_data', sa.Column('todo_id', sa.Integer(), nullable=False))
    op.add_column('fetched_data', sa.Column('title', sa.Text(), nullable=False))
    op.add_column('fetched_data', sa.Column('completed', sa.Boolean(), nullable=False))
    op.drop_column('fetched_data', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fetched_data', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('fetched_data', 'completed')
    op.drop_column('fetched_data', 'title')
    op.drop_column('fetched_data', 'todo_id')
    op.drop_column('fetched_data', 'user_id')
    # ### end Alembic commands ###
